GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/61407f970afb6098529514e1

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
	"name": "Lucy Who",
	"subscribedToChannel": "Web dev Simplified"
}

###
###
PATCH http://localhost:3000/subscribers/61407f970afb6098529514e1
Content-Type: application/json

{
	"name": "Lucy Who?"
}

###
DELETE http://localhost:3000/subscribers/61407f970afb6098529514e1
